Name: PRODUCTobjectClass
ignoreDependencies: false
VlocityDataPackKeys:
    - ObjectClass/63ba6ae5f8c257f7cdccc385d2a85dca
    - ObjectLayout/bf0f46e542a48b4b4443476d54301322
    - UIFacet/885e10262c2299afdcd1aa6e95138717
    - UIFacet/ba5c8ed8892b4b7bf7eda93d6207f828
    - UIFacet/88133f31931c2d3463baa8f14230978f
    - UISection/885e10262c2299afdcd1aa6e95138717
    - UISection/ba5c8ed8892b4b7bf7eda93d6207f828
    - UISection/88133f31931c2d3463baa8f14230978f
    - objects/OrderItem/fields/ARTL_PMLOCApproved__c.field
    - objects/OrderItem/fields/ARTL_PMApproved__c.field
VlocityTypesToFetch:
    - ObjectClass
    - ObjectLayout
    - UIFacet
    - UISection
    - VlocityUILayout
SalesforceTypesToFetch:
    - CustomField